// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'pt';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	/**
	 * T​h​i​s​ ​p​r​o​j​e​c​t​ ​w​a​s​ ​g​e​n​e​r​a​t​e​d​ ​w​i​t​h​ ​d​a​r​t​-​p​a​c​o​t​e​s​/​.​b​r​i​c​k​s​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​d​a​r​t​-​p​a​c​o​t​e​s​/​.​b​r​i​c​k​s​/​t​r​e​e​/​m​a​s​t​e​r​/​a​p​l​i​c​a​c​a​o​-​w​e​b
	 */
	greetings: string;
	/**
	 * R​e​a​d​ ​U​R​L
	 */
	urlLabel: string;
	/**
	 * T​i​t​l​e
	 */
	titleLabel: string;
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	descriptionLabel: string;
	/**
	 * I​n​t​r​o​d​u​c​t​i​o​n
	 */
	introductionLabel: string;
	/**
	 * S​u​m​m​a​r​y
	 */
	summaryLabel: string;
	/**
	 * K​e​y​w​o​r​d​s
	 */
	keywordsLabel: string;
	/**
	 * s​e​p​a​r​a​t​e​ ​w​i​t​h​ ​c​o​m​m​a​ ​(​,​)
	 */
	keywordsTootipTitle: string;
	/**
	 * D​r​a​f​t
	 */
	draftLabel: string;
	/**
	 * G​e​n​e​r​a​t​e​ ​R​e​a​d
	 */
	generateButton: string;
	/**
	 * C​o​p​y​ ​t​o​ ​c​l​i​p​b​o​a​r​d
	 */
	copyToClipboard: string;
	/**
	 * D​o​w​n​l​o​a​d​ ​a​s​ ​f​i​l​e
	 */
	exportToFile: string;
};

export type TranslationFunctions = {
	/**
	 * This project was generated with dart-pacotes/.bricks: https://github.com/dart-pacotes/.bricks/tree/master/aplicacao-web
	 */
	greetings: () => LocalizedString;
	/**
	 * Read URL
	 */
	urlLabel: () => LocalizedString;
	/**
	 * Title
	 */
	titleLabel: () => LocalizedString;
	/**
	 * Description
	 */
	descriptionLabel: () => LocalizedString;
	/**
	 * Introduction
	 */
	introductionLabel: () => LocalizedString;
	/**
	 * Summary
	 */
	summaryLabel: () => LocalizedString;
	/**
	 * Keywords
	 */
	keywordsLabel: () => LocalizedString;
	/**
	 * separate with comma (,)
	 */
	keywordsTootipTitle: () => LocalizedString;
	/**
	 * Draft
	 */
	draftLabel: () => LocalizedString;
	/**
	 * Generate Read
	 */
	generateButton: () => LocalizedString;
	/**
	 * Copy to clipboard
	 */
	copyToClipboard: () => LocalizedString;
	/**
	 * Download as file
	 */
	exportToFile: () => LocalizedString;
};

export type Formatters = {};
